image:
  organization: {{ parasol_store_image_registry_organization }}
  host: {{ parasol_store_image_registry_host }}
  name: {{ parasol_store_image_registry_image_name }}
  tag: {{ parasol_store_image_registry_image_tag }}

registry:
  username: {{ parasol_store_image_registry_username }}
  password: {{ parasol_store_image_registry_password }}

nameOverride: "parasol-store"

database:
  name: parasol-db
  secret:
    name: parasol-db
